early return

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -46,19 +46,20 @@ jobs:
         run: |
           set -u
 
-          echo "assets output:"
           echo "$ASSETS" | jq .
 
-          if [[ '1' = "$CHECK_URL" ]]; then
-            echo ""
-            echo "Expected URL pattern: .../releases/download/${{ github.ref_name }}/asset.txt"
-            echo "If the URL above contains 'untagged-' instead of the tag name, the bug is present."
+          if [[ '0' = "$CHECK_URL" ]]; then
+            exit 0
+          fi
 
-            browser_download_url="$( echo "$ASSETS" | jq --raw-output '.[0].browser_download_url' )"
+          echo ""
+          echo "Expected URL pattern: .../releases/download/${{ github.ref_name }}/asset.txt"
+          echo "If the URL above contains 'untagged-' instead of the tag name, the bug is present."
 
-            echo "$browser_download_url" | grep -P 'untagged-[a-z0-9]{20}'
-            if [[ '0' = "$?" ]]; then
-              echo "::error title=Wrong 'browser_download_url'::$browser_download_url"
-              exit 1
-            fi
+          browser_download_url="$( echo "$ASSETS" | jq --raw-output '.[0].browser_download_url' )"
+
+          echo "$browser_download_url" | grep -P 'untagged-[a-z0-9]{20}'
+          if [[ '0' = "$?" ]]; then
+            echo "::error title=Wrong 'browser_download_url'::$browser_download_url"
+            exit 1
           fi
